/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import webserver.Webserver;

public class App {
    public static void main(String[] args) {

        Webserver webserver = new Webserver("/");

        webserver.listen(8080);
        System.out.println("we are listening");
    }
}
