/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Webserver;

import java.io.IOException;
import java.net.ServerSocket;

public class Webserver {
    public String path;
    public Webserver(String path) {
        this.path = path;
        System.out.println("hello");
    }

    public void listen(Integer port)  {
        ServerSocket MyService;
        try {
            MyService = new ServerSocket(port);
        }

        catch (IOException e) {
            System.out.println(e);
        }
    }
}
