/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Webserver;
public class Webserver {
    public String path;
    public Webserver(String path) {
        this.path = path;
        System.out.println("hello");
    }

    public void listen(Integer port)  {
        System.out.println("hello");
    }
}
