/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webserver;

import java.io.*;
import java.net.ServerSocket;
import java.util.function.BiFunction;
import java.util.function.Function;
//import java.net.Socket;

public class Socket {
    private BiFunction<InputStream, OutputStream, Void> callback;

    public Socket(BiFunction<InputStream, OutputStream, Void> callback) {
        this.callback = callback;
    }

    public void listen(Integer port) throws IOException {
        new Thread(() -> {
            try {
                ServerSocket socket = new ServerSocket(port);
                socket.setReuseAddress(true);
                java.net.Socket clientSocket = socket.accept();
                InputStream inputStream = clientSocket.getInputStream();
                OutputStream outputStream = clientSocket.getOutputStream();

                this.callback.apply(inputStream, outputStream);
            } catch (IOException e) {
                System.out.println(e);
            }
        }).start();
    }
}
