package acceptance;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import webserver.Webserver;
import org.junit.Test;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.File;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.Buffer;

import static org.junit.Assert.assertEquals;

public class WebserverTest {
    @Test public void testAppRespondsWithHomepage() throws IOException {
        try {
            String publicDirectory = new File("../fixtures/homepage").getAbsolutePath();
            Webserver webserver = new Webserver(publicDirectory );

            webserver.listen(8080);

            URL url = new URL("http://localhost:8080/index.html");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");
            con.connect();

            BufferedReader reader = new BufferedReader(new InputStreamReader(con.getInputStream()));
            StringBuilder stringBuilder = new StringBuilder();

            String line = null;
            while ((line = reader.readLine()) != null) {
                stringBuilder.append(line + "\n");
            }

            String responseBody = stringBuilder.toString();
//        BufferedReader in = new BufferedReader(
//          new InputStreamReader(con.getInputStream())
//        );
//
//        String inputLine;
//        StringBuffer content = new StringBuffer();
//        while ((inputLine = in.readLine()) != null) {
//            content.append(inputLine);
//        }
//
//        in.close();
            reader.close();

            assertEquals(responseBody, "<article>Hello World</article>\n");
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}