//package acceptance;/*
// * This Java source file was generated by the Gradle 'init' task.
// */
//
//import Webserver.Webserver;
//import org.junit.Test;
//
//import java.io.BufferedReader;
//import java.io.IOException;
//import java.io.InputStreamReader;
//import java.io.File;
//import java.net.HttpURLConnection;
//import java.net.URL;
//
//import static org.junit.Assert.assertEquals;
//
//public class WebserverTest {
//    @Test public void testAppRespondsWithHomepage() throws IOException {
//        String publicDirectory = new File("../fixtures/homepage").getAbsolutePath();
//        Webserver webserver = new Webserver(publicDirectory );
//
//        webserver.listen(8080);
//
//        URL url = new URL("http://localhost:8080/index.html");
//        HttpURLConnection con = (HttpURLConnection) url.openConnection();
//        con.setRequestMethod("GET");
//
//        BufferedReader in = new BufferedReader(
//          new InputStreamReader(con.getInputStream())
//        );
//
//        String inputLine;
//        StringBuffer content = new StringBuffer();
//        while ((inputLine = in.readLine()) != null) {
//            content.append(inputLine);
//        }
//
//        in.close();
//
//        assertEquals(content, "<article>Hello World</article>");
//    }
//}
